config/routes.rb
Rails.application.routes.draw do
  get 'inicio/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :mesas
 
  root 'inicio#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/mesa.rb
class Mesa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/mesas_controller.rb
class MesasController < ApplicationController
    
    def index
        @mesas = Mesa.all
    end

   
    def new
    @mesa = Mesa.new
    end
   
    def edit
    @mesa = Mesa.find(params[:id])
    end 

    def create
        #@mesa = Mesa.new(params[:mesa])

        @mesa = Mesa.new(params.require(:mesa).permit(:modelo, :marca, :caract, :dim, :patas))
        if @mesa.save
        redirect_to @mesa
        else
        render 'new'
        end
    end

    def show
        @mesa = Mesa.find(params[:id])
      end

    def update
        @mesa = Mesa.find(params[:id])
       
        if @mesa.update(mesa_params)
          redirect_to @mesa
        else
          render 'edit'
        end
      end

      def destroy
        @mesa = Mesa.find(params[:id])
        @mesa.destroy
     
        redirect_to mesas_path
      end
       
      private
        def mesa_params
          params.require(:mesa).permit(:modelo, :marca, :caract, :dim, :patas)
        end

   
    


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/mesas_helper.rb
module MesasHelper
end

app/views/inicio/index.html.erb
<h1>ResIT</h1>
<h2>  Acceso Central Mesas </h2>
<%= link_to 'Registro Mesas', controller: 'mesas' %>

<h2>  Agregar nueva mesa  </h2>
<%= link_to 'Nueva Mesa', new_mesa_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mesas</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
 
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mesas/edit.html.erb
<h1>Editar Mesa</h1>
 
<%= form_with(model: @mesa, local: true) do |form| %>
 
  <% if @mesa.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@mesa.errors.count, "error") %> prohibited
        this mesa from being saved:
      </h2>
      <ul>
        <% @mesa.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :Modelo %><br>
    <%= form.text_field :modelo %>
  </p>

  <p>
  <%= form.label :Marca %><br>
  <%= form.text_field :marca %>
</p>
 
  <p>
    <%= form.label :Características %><br>
    <%= form.text_area :caract %>
  </p>

  <p>
  <%= form.label :Dimensiones %><br>
  <%= form.text_field :dim %>
</p>
 
<p>
<%= form.label :Patas %><br>
<%= form.number_field :patas %>
</p>

  <p>
    <%= form.submit :Actualizar%>
  </p>
 
<% end %>
 
<%= link_to 'Regresar', mesas_path %>

app/views/mesas/index.html.erb
<h1>Lista de mesas</h1>
 
<table>
  <tr>
    <th>Modelo</th>
    <th>Marca</th>
    <th colspan="3"></th>
  </tr>
 
  <% @mesas.each do |mesa| %>
    <tr>
      <td><%= mesa.modelo %></td>
      <td><%= mesa.marca %></td>
      <td><%= link_to 'Show', mesa_path(mesa) %></td>
      <td><%= link_to 'Edit', edit_mesa_path(mesa) %></td>
      <td><%= link_to 'Destroy', mesa_path(mesa),
      method: :delete,
      data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<br>

<%= link_to 'Regresar Inicio', root_path %>

app/views/mesas/new.html.erb
<%= form_with scope: :mesa, url: mesas_path, local: true do |form| %>
    <p>
      <%= form.label :Modelo %><br>
     <%= form.text_field :modelo %><br>
      <%= form.label :Marca %><br>
      <%= form.text_field :marca %> <br>
      <%= form.label :Características %><br>
      <%= form.text_area :caract %> <br>
      <%= form.label :Dimensiones %><br>
      <%= form.text_field :dim %> <br>
      <%= form.label :Patas %><br>
      <%= form.number_field :patas %> <br>
     

    
    </p>
   
    <p>
     
   
    </p>
   
    <p>
      <%= form.submit :Guardar %>
    </p>
  <% end %>

  <%= link_to 'Regresar', mesas_path %>

app/views/mesas/show.html.erb
<p>
<strong>Modelo:</strong>
<%= @mesa.modelo %>
</p>

<p>
<strong>Marca:</strong>
<%= @mesa.marca %>
</p>

<p>
<strong>Características:</strong>
<%= @mesa.caract %>
</p>

<p>
<strong>Dimensiones:</strong>
<%= @mesa.dim %>
</p>

<p>
<strong>Patas:</strong>
<%= @mesa.patas %>
</p>

<%= link_to 'Regresar', mesas_path %>